inherit_from: .rubocop_todo.yml

inherit_gem:
  simplycop:
    - .simplycop.yml
    - .simplycop_performance.yml
    - .simplycop_rspec.yml

AllCops:
  TargetRubyVersion: 3.1.2
Metrics/BlockLength:
  Max: 250
Metrics/AbcSize:
  Max: 25
Metrics/MethodLength:
  Max: 25
