apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: deploy-status-action
  title: Deploy Status Action
  description: GitHub Action to provide status and ability to block releases by creating an issue
spec:
  type: github action
  lifecycle: production
  dependsOn:
    - "Resource:github-actions"
  consumesAPI:
    - github-rest-api
  system: github
