name: "Dependabot auto approve and merge"
on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    branches:
      - master

permissions:
  pull-requests: write
  contents: write

jobs:
  dependabot-auto-merge-all:
    uses: simplybusiness/github-action-reusable-workflows/.github/workflows/dependabot-auto-approve-and-merge-minor-patch.yaml@v1
    with:
      pr_url: ${{ github.event.pull_request.html_url }}
      actor: ${{ github.actor }}
    secrets:
      github-token: ${{secrets.SB_SILVERSMITHS_BOT}}
